### ISSUE TITLE
[Missing] data interfaces should provide a property to ensure `database_requested` has run

### ISSUE THREAD

**Issue by Gu1nness** [canonical/data-platform-libs#193]
If a charm needs to do some updates of the stored data/secrets in a `relation_changed` event for example, it has to check that the `database_requested` event has run. Currently, there is no documentation on how to do that, nor a property or a check function to do that.

Adding a `is_relation_setup` or equivalent + the according documentation and a small example should do the thing.

**Comment by juditnovak** [comment]
Thank you very much for reporting. Indeed it's a serious concern.

Instead of property + docs what we provide is the following: as long as the `database` field is not set on the relation, the `Provicer` (the side creating secrets) will not be allowed to apply write operation.

If the `Provider` would make an attempt to execute` update_relation_data()` it would throw an exception indicating that the opration is premature.
